In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("C:\\Users\\Trivikram\\ML_Projects\\Data\\CityBlock.csv")

In [3]:
df

X   Y
0  2  10
1  2   5
2  8   4
3  5   8
4  7   5
5  6   4
6  1   2
7  4   9

In [4]:
k=int(input("How many clusters do you want? "))

How many clusters do you want? 3


In [5]:
centroids=[]
while(len(np.unique(centroids))!=k):
    centroids=np.random.randint(low=0,high=6,size=k)
centroids=np.asarray(df.iloc[centroids])
noOfCol=len(df.columns)
prev=np.asarray([np.zeros(noOfCol)]*k)

In [6]:
previousClusters=[0]*k
clusters=[1]*k

In [7]:
print(centroids)

[[ 6  4]
 [ 2  5]
 [ 2 10]]


In [15]:
while previousClusters!=clusters:
    distance=df.copy()
    distance.columns=range(k)
    for i in distance.columns:
        for j in range(df.shape[0]):
            distance[i][j]=np.sqrt(sum((np.subtract(centroids[i],df.iloc[j].tolist()))**2))
    previousClusters=clusters
    clusters=distance.idxmin(axis=1).tolist()
    indexes= [[i for i, value in enumerate(clusters) if value == j]for j in range(k)]
    centroids=np.asarray([df.iloc[i].mean().tolist() for i in indexes])


In [16]:
centroids

array([[1.25, 1.5 ],
       [3.9 , 5.1 ]])

In [19]:
distance=df.copy()
distance.columns=range(k)


In [29]:
while previousClusters!=clusters:
    dis=[[np.sqrt(sum((np.subtract(centroids[i],df.iloc[j].tolist()))**2)) for j in range(df.shape[0])] for i in range(k)]
    distance=pd.DataFrame(dis).T    #Transpose
    previousClusters=clusters
    clusters=distance.idxmin(axis=1).tolist()
    indexes= [[i for i, value in enumerate(clusters) if value == j]for j in range(k)]
    centroids=np.asarray([df.iloc[i].mean().tolist() for i in indexes])

In [30]:
centroids

array([[1.25, 1.5 ],
       [3.9 , 5.1 ]])